#!/bin/bash
################################################################################
#                                  deploy                                      #
################################################################################
#                                                                              #
#  DESCRIPTION:  Quick script to consistently and reliably upload releases     #
#                to our website.                                               #
#                                                                              #
#  AUTHOR:       Mark Zieg <mzieg@wasatchphotonics.com>                        #
#                                                                              #
################################################################################

# see https://www.reddit.com/r/Xamarin/comments/ftsrez/androidmanifestxml_versionname_vs_assemblyinfocs/
function checkVersion()
{
    local VERSION="$1"

    local PROJ="EnlightenMobile.Android/EnlightenMobile.Android.csproj"
    local SLN="EnlightenMobile.sln"
    local ASM="EnlightenMobile.Android/Properties/AssemblyInfo.cs"
    local XML="EnlightenMobile.Android/Properties/AndroidManifest.xml"

    if grep -q "version = $VERSION" $SLN
    then
        echo "$VERSION found in $SLN"
    else
        echo "ERROR: could not find $VERSION in $SLN"
        exit 1
    fi

    if grep -q "<ReleaseVersion>$VERSION</ReleaseVersion>" $PROJ
    then
        echo "$VERSION found in $PROJ"
    else
        echo "ERROR: could not find $VERSION in $PROJ"
        exit 1
    fi
    
    if grep -q "android:versionName=\"$VERSION\"" $XML
    then
        echo "$VERSION found in $XML"
    else
        echo "ERROR: could not find $VERSION in $XML"
        exit 1
    fi

    # don't worry about AssemblyInfo for now
    #     [assembly: AssemblyVersion("0.2.5.0")]
    #     [assembly: AssemblyFileVersion("0.2.5.0")]
}

function checkGit()
{
    local VERSION="$1"
    if git tag | egrep -q $VERSION
    then
        echo "Found Git tag $VERSION"
    else
        echo "Git tag not found: $VERSION"
        exit 1
    fi
}

function post()
{
    local VERSION="$1"

    local LOCAL_PATH="com.wasatchphotonics.enlightenmobile.apk"
    local LOCAL_NAME="enlighten-${VERSION}.apk"
    local REMOTE_PATH="www/binaries/oem/sig/$LOCAL_NAME"

    if ! [ -f $LOCAL_PATH ]
    then
        echo "ERROR: can't find $LOCAL_PATH"
        exit 1
    fi

    mkdir -p releases
    mv -f -v $LOCAL_PATH releases/$LOCAL_NAME

    scp releases/$LOCAL_NAME $USERNAME@wasatchphotonics.com:$REMOTE_PATH
}

read -p "Username: " USERNAME
read -p "Version:  " VERSION 

checkVersion $VERSION
checkGit $VERSION
post $VERSION
